$bg         = rgb(121212)
$bg2        = rgb(504945)
$fg         = rgb(d5d5d5)
$fg1        = rgb(b4b4b4)
$red        = rgb(B14242)
$yellow     = rgb(E49A44)
$blue       = rgb(4A8B8B)
$orange     = rgb(D87C4A)
