source = ~/.config/hypr/color.conf

background       = $bg
base             = $bg1
text             = $fg1
alternate_base   = $bg2
bright_text      = $fg
accent           = $green
accent_secondary = $blue

icon_theme = "Gruvbox-Plus-Dark"
font_family = "BlexMono Nerd Font Propo"
font_family_monospace = "BlexMono Nerd Font Mono"
